using Test, JSON, Random, Base64

# Servo.Crypt is loaded via `using Servo` in runtests.jl.
const C = Servo.Crypt

@testset "Crypt: Jasypt PBEWITHHMACSHA512ANDAES_256 parity" begin

    # ---- Oracle 1: PBKDF2-HMAC-SHA512 against independent known answers ----
    # Values produced by Python's hashlib.pbkdf2_hmac('sha512', ...), which is an
    # implementation entirely separate from this one and from Java/aws-c-cal.
    @testset "PBKDF2-HMAC-SHA512 known answers" begin
        @test bytes2hex(C.pbkdf2_hmac_sha512(b"password", b"salt", 1, 32)) ==
            "867f70cf1ade02cff3752599a3a53dc4af34c7a669815ae5d513554e1c8cf252"
        @test bytes2hex(C.pbkdf2_hmac_sha512(b"password", b"salt", 2, 32)) ==
            "e1d9c16aa681708a45f5c7c4e215ceb66e011a2e9f0040713f18aefdb866d53c"
        @test bytes2hex(C.pbkdf2_hmac_sha512(b"password", b"salt", 4096, 32)) ==
            "d197b1b33db0143e018b12f3d1d1479e6cdebdcc97c5c0f87f6902e072f457b5"
        @test bytes2hex(C.pbkdf2_hmac_sha512(b"passwordPASSWORDpassword",
                b"saltSALTsaltSALTsaltSALTsaltSALTsalt", 4096, 40)) ==
            "8c0511f4c6e597c6ac6315d8f0362e225f3c501495ba23b868c005174dc4ee71115b59f9e60cd953"
        @test_throws ArgumentError C.pbkdf2_hmac_sha512(b"p", b"s", 0, 32)
    end

    # ---- Oracle 2: byte-for-byte parity with REAL Java Jasypt 1.9.3 ----
    # fixtures/jasypt_vectors.jsonl was generated by encrypting with the actual
    # org.jasypt:jasypt:1.9.3 StandardPBEStringEncryptor configured exactly as the
    # production code (PBEWITHHMACSHA512ANDAES_256, 50000 iters, SunJCE), with fixed
    # salt/iv so the output is reproducible. See fixtures/JasyptVectors.java.
    vectors = [JSON.parse(l) for l in eachline(joinpath(@__DIR__, "fixtures", "jasypt_vectors.jsonl")) if !isempty(strip(l))]
    @test length(vectors) >= 100

    @testset "encrypt is byte-identical to Jasypt" begin
        for v in vectors
            pw = String(hex2bytes(v["password_hex"])); pt = String(hex2bytes(v["plaintext_hex"]))
            salt = hex2bytes(v["salt_hex"]); iv = hex2bytes(v["iv_hex"]); iters = Int(v["iters"])
            @test C.jasypt_encrypt(pw, pt; iterations=iters, salt=salt, iv=iv) == v["ct_b64"]
        end
    end

    @testset "decrypt recovers Jasypt plaintext" begin
        for v in vectors
            pw = String(hex2bytes(v["password_hex"])); pt = String(hex2bytes(v["plaintext_hex"])); iters = Int(v["iters"])
            got = C.jasypt_decrypt(pw, v["ct_b64"]; iterations=iters)
            @test collect(codeunits(got)) == collect(codeunits(pt))
        end
    end

    # ---- Oracle 3: self-consistent round-trip on random inputs ----
    @testset "round-trip (random salt/iv)" begin
        rng = Random.MersenneTwister(0x5E2F0)
        for _ in 1:60
            pw = randstring(rng, rand(rng, 1:32))
            pt = randstring(rng, rand(rng, 0:256))
            its = rand(rng, (1000, 10000))
            @test C.jasypt_decrypt(pw, C.jasypt_encrypt(pw, pt; iterations=its); iterations=its) == pt
        end
    end

    @testset "ENC(...) wrapper accepted on decrypt" begin
        ct = C.jasypt_encrypt("rotation-key", "s3cr3t-value")
        @test C.jasypt_decrypt("rotation-key", "ENC(" * ct * ")") == "s3cr3t-value"
    end

    @testset "wrong key never recovers the plaintext" begin
        # aws-c-cal validates PKCS5 padding on some backends (libcrypto) but not others
        # (CommonCrypto), so a wrong key may throw OR return garbage — but never the original.
        ct = C.jasypt_encrypt("right", "super-secret")
        for k in ("wrong", "righ", "Right", "right ", "")
            got = nothing
            threw = try; got = C.jasypt_decrypt(k, ct); false; catch; true; end
            @test threw || got != "super-secret"
        end
    end

    @testset "malformed ciphertext is rejected" begin
        @test_throws ArgumentError C.jasypt_decrypt("k", base64encode(rand(UInt8, 10)))  # < salt+iv+block
    end
end
